# Generated by Django 2.0 on 2018-11-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author of Message')),
                ('whom', models.CharField(max_length=100, verbose_name='Recipient of Message')),
                ('text', models.CharField(blank=True, max_length=500, verbose_name='Text of Message')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Date of message created')),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'verbose_name': 'Messages',
            },
        ),
    ]
