# Generated by Django 2.0 on 2018-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_auto_20181123_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_model',
            name='status',
            field=models.CharField(default='not read', max_length=10, verbose_name='Status of message'),
        ),
    ]
